//DEPLOYMENT
export const PULL_REQUEST_DEPLOY_START = 'PULL_REQUEST_DEPLOY_START';
export const PULL_REQUEST_DEPLOY_END = 'PULL_REQUEST_DEPLOY_END';
//PRS
export const LOAD_PULL_REQUEST_LIST_START = 'LOAD_PULL_REQUEST_LIST_START';
export const LOAD_PULL_REQUEST_LIST_END = 'LOAD_PULL_REQUEST_LIST_END';
//SYSTEM
export const INITIALIZATION_TOOLS = 'INITIALIZATION_TOOLS';
//BRANCHES
export const LOAD_BRANCHES_START = 'LOAD_BRANCHES_START';
export const LOAD_BRANCHES_END = 'LOAD_BRANCHES_END';
//MESSAGES
export const ADD_FLASH_MESSAGE = 'ADD_FLASH_MESSAGE';
export const DELETE_FLASH_MESSAGE = 'DELETE_FLASH_MESSAGE';
//USER
export const LOAD_USER_ORGANIZATIONS_INFO_START = 'LOAD_USER_ORGANIZATION_INFO_START';
export const LOAD_USER_ORGANIZATIONS_INFO_END = 'LOAD_USER_ORGANIZATION_INFO_END';
export const SET_USER_TOKEN = 'SET_USER_TOKEN';
//PORTING
export const PORTING_PULL_REQUEST_START = 'PORTING_PULL_REQUEST_START';
export const PORTING_PULL_REQUEST_END = 'PORTING_PULL_REQUEST_END';
export const SET_PORTING_SETTINGS = 'SET_PORTING_SETTINGS';
export const LOAD_PORTING_JOBS_START = 'LOAD_PORTING_JOBS_START';
export const LOAD_PORTING_JOBS_END = 'LOAD_PORTING_JOBS_END';
export const LOAD_PORTING_JOBS_ARTIFACTS_START = 'LOAD_PORTING_JOBS_ARTIFACTS_START';
export const LOAD_PORTING_JOBS_ARTIFACTS_END = 'LOAD_PORTING_JOBS_ARTIFACTS_END';
export const ADD_PORTING_JOB = 'ADD_PORTING_JOB';
//AUTHORIZATION
export const LOAD_AUTHORIZATION_URL_START = 'LOAD_AUTHORIZATION_URL_START';
export const LOAD_AUTHORIZATION_URL_END = 'LOAD_AUTHORIZATION_URL_END';
//LOADING
export const LOADING_PROCESS_START = 'LOADING_PROCESS_START';
export const LOADING_PROCESS_END = 'LOADING_PROCESS_END';
